### PR TITLE
fix: improve actionable API error messages

### LINKED ISSUE #334: Improve API-level error messages
From Anthropic:

> When the Todoist API returns errors, the MCP server surfaces generic messages like "HTTP 400: Bad Request" or "Tool call failed: 500" with no additional context. These are not actionable for the LLM or the end user. By contrast, your Zod-based input validation errors are excellent — they include the exact field path, expected types, and valid options. We'd like to see the same level of detail for API-level errors.

### PR DESCRIPTION
**Pull request by gnapse**
# Pull Request

Closes #334

## Short description

Centralizes API-originated error formatting for MCP tool execution by routing catch-path handling through a new `tool-execution-error` module. The formatter now includes HTTP status/code/tag, API message/details, field hints, and short next-step guidance while redacting token-like secrets. Zod validation errors still pass through unchanged, and successful tool responses are unchanged. Added focused tests for formatter behavior and MCP wrapper integration.

## PR Checklist

Feel free to leave unchecked or remove the lines that are not applicable.

-   [x] Added tests for bugs / new features
-   [x] ~~Updated docs (README, etc.)~~ N/A
-   [x] ~~New tools added to `getMcpServer` AND exported in `src/index.ts`.~~ N/A

### 1) Generic API error (HTTP 400)

**Before**
```text
HTTP 400: Bad Request
```

**After**
```text
Todoist API request failed (HTTP 400).
Message: HTTP 400: Bad Request
Try next: Check parameter values and formats, then retry.
```

### 2) Structured API validation-style error

**Before**
```text
An unknown error occurred
```

**After**
```text
Todoist API request failed (HTTP 400, code 42, tag INVALID_ARGUMENT).
Message: Invalid due date format
Details: Use natural language (e.g., "tomorrow") or YYYY-MM-DD.
Field hints: dueString
Try next: Fix the field hints above and retry.
```

### 3) Auth-related error with sensitive value in payload

**Before**
```text
Unauthorized
Authorization: Bearer secret_token_123456789 ...
```

**After**
```text
Todoist API request failed (HTTP 401).
Message: Unauthorized
Details: Authorization: Bearer [REDACTED] and token: [REDACTED]
Try next: Verify your API token and access permissions, then retry.
```

### 4) Zod input validation (unchanged behavior)

**Before**
```text
<Zod validation message>
```

**After**
```text
<Same Zod validation message (unchanged)>
```

### CODE REVIEW

File: src/tool-execution-error.ts [hunk 1]
```diff
@@ -0,0 +1,414 @@
...
+        summarizeDetails(responseData?.errorDetails),
+        summarizeDetails(responseData?.errors),
+        summarizeDetails(errorRecord?.details),
+    )
+
+    const fieldHints = extractFieldHints(responseData)
+
+    const hasApiSignals =
+        statusCode !== undefined ||
+        responseData !== undefined ||
```
[the remark this answers is not in the document]
Comment (gnapse) [reply src/tool-execution-error.ts]: Valid, it is now fixed.

File: src/tool-execution-error.ts [hunk 2]
```diff
@@ -0,0 +1,434 @@
...
+
+    return Array.from(hints).slice(0, 3)
+}
+
+const KNOWN_API_ERROR_KEYS = [
+    'error',
+    'errorCode',
+    'errorTag',
+    'errors',
+    'errorDetails',
```
Comment (nats12) [inline src/tool-execution-error.ts]: 💭: I'm not sure if we have control over these, but they all seem very similar, creating some ambiguity as to why we need all of these. I.e. is `error` the full object, containing the others? Does `errorDetails` contain code or tag? We may at least want to document each.

File: src/tool-execution-error.ts [hunk 3]
```diff
@@ -0,0 +1,434 @@
...
+
+function firstRecord(...values: unknown[]): Record<string, unknown> | undefined {
+    return values.find(isRecord)
+}
+
+function firstDefined<T>(...values: Array<T | undefined>): T | undefined {
+    return values.find((value): value is T => value !== undefined)
+}
+
+function toNumber(value: unknown): number | undefined {
```
Comment (nats12) [inline src/tool-execution-error.ts:24]: Some of these `toNumber`, `toCode` etc, although used exclusively here in the tool execution error seem quite generic. We may want to shift the responsibility out of this file.

Comment (gnapse) [reply src/tool-execution-error.ts:24]: I'm hesitant to preemptively move things that look like they're reusable. I'd rather tolerate a bit of duplication if by chance similar helpers appear elsewhere, and we'll eventually notice, especially in this small codebase.

File: src/tool-execution-error.ts (hunk 2 above)
Comment (gnapse) [reply src/tool-execution-error.ts]: Valid feedback. I launched an agent to find Todoist API documentation and other sources, and nailed this down to a more confirmed list of things we can expect and look for in the error payloads. Plus it made the code a bit more documented on this regard.
